Repository GauravKarakoti/Colour-Segmentation, pull requests merged in 2025-03, with the labels that each got.

#14 Added pr and issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: medium, apertre2.0

#15 Add Error Handling for File I/O
  .gitignore
  img_segment.py
  segment.py
Labels: bug, enhancement, hard, apertre2.0

#17 Allow Configurable File Paths
  img_segment.py
  segment.py
Labels: enhancement, medium, apertre2.0, usability

#21 feat: RGB display and save functionality
  palette.py
Labels: bug, enhancement, medium, apertre2.0

#23 Text Visibility on Bright Backgrounds
  palette.py
Labels: medium, apertre2.0

#33 Create License.md
  License.md
Labels: doc, apertre2.0

#34 Create Security.md
  Security.md
Labels: doc, apertre2.0

#35 Create Code of Conduct.md
  Code of Conduct.md
Labels: doc, apertre2.0

#37 Fix : Saved color image does not include RGB text overlay
  .gitignore
  palette.py
Labels: easy, apertre2.0

#45 added code comments
  .vscode/settings.json
  img_segment.py
  palette.py
  segment.py
Labels: enhancement, easy, apertre2.0

#46 Dockerize the application
  Contributing.md
  Dockerfile
Labels: medium, apertre2.0

#48 improved ui in palette.py
  palette.py
Labels: medium, apertre2.0

#49 Critical Fixes Needed for Color Segmentation in HSV Space
  segmentation_utils.py
Labels: easy, apertre2.0

#52 Limited error handling for invalid/corrupted media files
  img_segment.py
  segment.py
  segmentation_utils.py
Labels: medium, apertre2.0

#54 Critical Hue Wrapping Issue in HSV Segmentation and Suggested Enhancements
  img_segment.py
  palette.py
  segment.py
  segmentation_utils.py
Labels: hard, apertre2.0

#56 Inconsistent Window Naming Across Segmentation Modes
  segmentation_utils.py
Labels: easy, apertre2.0

#57 ci workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  README.md
  tests/test_utils.py
Labels: enhancement, hard, apertre2.0, CI/CD, workflow

#60 Inability to Save Segmentation Results
  img_segment.py
  palette.py
  segment.py
Labels: easy, apertre2.0

#62 error handling
  img_segment.py
  segment.py
Labels: easy, apertre2.0

#64 hsv space conversion
  img_segment.py
  segment.py
Labels: bug, enhancement, easy, apertre2.0

#55 Enhancements and Improvements for Color Palette Application
  img_segment.py
  palette.py
Labels: hard, apertre2.0

#65 fix : Unmanaged Window Proliferation and Z-Order Issues
  img_segment.py
  segment.py
Labels: easy, apertre2.0

#67 fix: Redundant Morphology Operations in apply_mask Function
  segment.py
  segmentation_utils.py
Labels: easy, apertre2.0

#73 fix Bugs in Video Processing Loop and Trackbar Inconsistencies
  .gitignore
  segment.py
Labels: bug, enhancement, medium, apertre2.0, refactor

#78 Uncontrolled CPU Usage in Processing Loops
  img_segment.py
  palette.py
  segment.py
Labels: easy, apertre2.0

#83 scroll to top button
  README.md
Labels: doc, apertre2.0

#86 Add pause functionality to video processing loop
  segment.py
Labels: easy, apertre2.0

#87 Fix/resized resolution
  img_segment.py
  segment.py
Labels: easy, apertre2.0

#88 sorted functions
  segmentation_utils.py
Labels: easy, apertre2.0

#89 color space conversion
  img_segment.py
  segmentation_utils.py
Labels: easy, apertre2.0

#91 Morphological Operations
  segment.py
Labels: easy, apertre2.0

#100 adding a default filename
  palette.py
Labels: easy, apertre2.0

#104 streamlit-py
  app.py
  img_segment.py
  segmentation_utils.py
  temp_video.mp4
Labels: hard, apertre2.0

#103 Refactor root instance handling and improve non-blocking window behavior
  palette.py
Labels: medium, apertre2.0

#115 fix Incompatible Video Codec and File Extension in segment.py
  segment.py
  segmentation_utils.py
Labels: easy, apertre2.0

#116 Colour correction
  color_checking.py
  images/red.jpeg
  img_segment.py
  palette.py
Labels: medium, apertre2.0

#118 streamlit-UI #114
  app.py
Labels: easy, apertre2.0

#120 Add kernel size slider and apply morphological operations to results
  app.py
Labels: medium, apertre2.0

#119 Fix Inefficient Frame Timing Control Leading to High CPU Usage or Lag
  img_segment.py
  palette.py
  segment.py
  segmentation_utils.py
Labels: easy, apertre2.0
