Repository GauravKarakoti/Colour-Segmentation, pull requests merged in 2025-04, with the labels that each got.

#121 error handling
  img_segment.py
  segment.py
  segmentation_utils.py
Labels: medium, apertre2.0

#125 added color palette
  .gitignore
  app.py
Labels: hard, apertre2.0

#136 save results
  img_segment.py
Labels: easy, apertre2.0

#142 fix: Potential Issues and Enhancements for Video Segmentation Script
  segment.py
Labels: hard, apertre2.0

#143 fix: z-order issue
  img_segment.py
Labels: easy, apertre2.0

#155 saving issue
  segment.py
Labels: easy, apertre2.0

#160 Fix/z order issue video
  segment.py
Labels: easy, apertre2.0

#158 all issues solved
  app.py
  mask_frame_0.png
  result_frame_0.png
  segmentation_utils.py
Labels: medium, apertre2.0
